[project]
name = ""
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.12.10"
dependencies = [
    "opencv-python==4.12.0.88",
    "numpy==2.0.2",
    "ultralytics==8.3.182",
    "lap==0.5.12",
    "easyocr==1.7.2",
    "pandas"

]
